apiVersion: v1
data:
  ARANGO_ROOT_PASSWORD: TestDB@home2
  ARANGO_STORAGE_ENGINE: rocksdb
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: arangodb-arangodb-docker-compose-env
  name: arangodb-docker-compose-env
