apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: customersrv
  name: customersrv
spec:
  ports:
  - name: "50057"
    port: 50057
    targetPort: 50057
  selector:
    io.kompose.service: customersrv
