apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nats
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: nats
    spec:
      containers:
      - image: nats
        imagePullPolicy: ""
        name: nats
        ports:
        - containerPort: 8222
        - containerPort: 4222
        - containerPort: 6222
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
#      volumes: null
