apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: promotionsrv
  name: promotionsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promotionsrv
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: promotionsrv
    spec:
      containers:
      - env:
        - name: DISABLE_AUDIT_RECORDS
          valueFrom:
            configMapKeyRef:
              key: DISABLE_AUDIT_RECORDS
              name: promotion-docker-compose-env
        - name: MICRO_BROKER
          valueFrom:
            configMapKeyRef:
              key: MICRO_BROKER
              name: promotion-docker-compose-env
        - name: MICRO_BROKER_ADDRESS
          valueFrom:
            secretKeyRef:
              key: MICRO_BROKER_ADDRESS
              name: promotionsrv-secret
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: promotion-docker-compose-env
        - name: MICRO_STORE
          valueFrom:
            configMapKeyRef:
              key: MICRO_STORE
              name: promotion-docker-compose-env
        - name: MICRO_STORE_ADDRESS
          valueFrom:
            secretKeyRef:
              key: MICRO_STORE_ADDRESS
              name: promotionsrv-secret
        - name: POSTGRES_CONNECT
          valueFrom:
            secretKeyRef:
              key: POSTGRES_CONNECT
              name: promotionsrv-secret
        image: bolbeck/gotemp_promotionsrv
        imagePullPolicy: ""
        name: promotionsrvcont
        ports:
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
